/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDslCStandaloneSetup extends MyDslCStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDslCStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
