/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.example.mydsl.myDslC.ModelC

@RunWith(XtextRunner)
@InjectWith(MyDslCInjectorProvider)
class MyDslCParsingTest {
	@Inject
	ParseHelper<ModelC> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Helloc Xtext a.b.c x.y.z
				Hello Xtext xyz!!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
